version: "3.9"

services:

  movie-match-postgres:
    image: postgres
    container_name: 'movie-match-postgres'
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 12200:5432